### ISSUE TITLE
Flaps 10

### ISSUE THREAD

**Issue by Midcon113** [dgtlanlg/C208B-mod#1]
Thanks for a great mod! Can we get the flaps back to having a 10 degree setting using the flap buttons? Right now, extending flaps with the F7 key sends them straight to Flaps 20.

**Comment by TrentKama** [comment]
The modern 208B EX has only 20/30 deg settings, it's intended. Technically it's set to 15/30 right now.

**Comment by Midcon113** [comment]
The latest reference material I have (the Flight Safety training manual) is
from 2008. Is there a more current POH or other similar material available?
I appreciate the update - I didn't know that!

**Comment by TrentKama** [comment]
[360482563-208BIMCUS-00-Pilot-Manual.pdf](https://github.com/dgtlanlg/C208B-mod/files/5762446/360482563-208BIMCUS-00-Pilot-Manual.pdf)
This is the latest one I've found.

**Comment by Midcon113** [comment]
Awesome, thanks!

**Comment by dcbryden** [comment]
The C208B has detentes for 10, 20 and 30 deg. flaps. The latest "EX" version did away with the 10 deg. detente, opting for the TO/AP (20 deg.) slot and the full (30 deg.) slot. HOWEVER the 10 deg. position is still marked and in fact any increment between 0 and 30 can be selected in the real aircraft. Edit the flight_model.cfg FLAPS section and add as many positions as you like. I have four detentes to match my 3D-printed flap insert for 0, 10, 20 & 30. Though just a notch at 20 and full would be more accurate but I would still add 10, 15, 20, 25 and 30 to the CFG file.
